"DbUser" = "#{PG_DbUser}#@#{PG_DbHost}#"
"DbPassword" = "#{PG_DbPassword}#"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "#{PG_DbHost}#.postgres.database.azure.com"
"ListenHost" = "localhost"
"ListenPort" = "3000"